CREATE TABLE "TBBANCO"
(
  "CODBANCO"	CHAR(3) NOT NULL,
  "NOME"	VARCHAR(75) NOT NULL,
CONSTRAINT "PK_CODBANCO" PRIMARY KEY ("CODBANCO"),
CONSTRAINT "UK_NOME_BANCO" UNIQUE ("NOME")
);

CREATE TABLE "TBUF"
(
  "CODUF"	CHAR(2) NOT NULL,
  "NOME"	VARCHAR(35) NOT NULL,
CONSTRAINT "PK_CODUF" PRIMARY KEY ("CODUF"),
CONSTRAINT "UK_NOME" UNIQUE ("NOME")
);

CREATE TABLE "TBCIDADE"
(
  "CODCIDADE"	DECIMAL(15,0) NOT NULL,
  "CODUF"	CHAR(2) NOT NULL,
  "NOME"	VARCHAR(35) NOT NULL,
CONSTRAINT "PK_CODCIDADE" PRIMARY KEY ("CODCIDADE")
);
ALTER TABLE "TBCIDADE" ADD CONSTRAINT "FK_UF" FOREIGN KEY ("CODUF") REFERENCES TBUF ("CODUF");

CREATE TABLE "TBAGENCIA"
(
  "CODAGENCIA"	VARCHAR(15) NOT NULL,
  "CODBANCO"	CHAR(3) NOT NULL,
  "NOMECONTATO"	VARCHAR(45),
  "NOME"	VARCHAR(45),
  "RUA"	        VARCHAR(45),
  "BAIRRO"	VARCHAR(45),
  "CODCIDADE"	DECIMAL(15,0) NOT NULL,
  "CEP"	VARCHAR(9),
  "TEL"	VARCHAR(10),
CONSTRAINT "PK_CODAGENCIA" PRIMARY KEY ("CODAGENCIA")
);
ALTER TABLE "TBAGENCIA" ADD CONSTRAINT "FK_CODBANCO_AGENCIA" FOREIGN KEY ("CODBANCO") REFERENCES TBBANCO ("CODBANCO");
ALTER TABLE "TBAGENCIA" ADD CONSTRAINT "FK_CODCIDADE_AGENCIA" FOREIGN KEY ("CODCIDADE") REFERENCES TBCIDADE ("CODCIDADE");

CREATE TABLE "TBPESSOA"
(
  "CODPESSOA"	DECIMAL(15,0) NOT NULL,
  "CODCIDRESID"	DECIMAL(15,0) NOT NULL,
  "CODUSUARIO"	DECIMAL(15,0) NOT NULL,
  "ENDERECO"	VARCHAR(45) default NULL,
  "COMPLEMENTO"	VARCHAR(25) default NULL,
  "BAIRRO"	VARCHAR(35) default NULL,
  "TEL"	VARCHAR(13) default NULL,
  "CEL"	VARCHAR(13) default NULL,
  "CEP"	VARCHAR(10) default NULL,
  "NOME"	VARCHAR(45) NOT NULL,
  "TIPOPESSOA"	CHAR(1) NOT NULL,
  "CPFCNPJ"	VARCHAR(18) NOT NULL,
  "EMAIL"	VARCHAR(70) default NULL,
  "WEB"	VARCHAR(70) default NULL,
  "DATACADASTRO"	DATE NOT NULL,
  "DATATUALIZACAO"	DATE NOT NULL,
  "RG"	VARCHAR(11) default NULL,
  "DATANASCIMENTO"	DATE,
  "SEXO"	CHAR(1),
  "OBS"	BLOB SUB_TYPE 0 SEGMENT SIZE 80,
  "TELRAMAL"	VARCHAR(5),
  "CODCIDADENACIMENTO"	DECIMAL(15,0),
  "DEFICIECIA"	VARCHAR(255),
  "ESTADOCIVIL"	DECIMAL(15,0),
  "FOTO"	BLOB SUB_TYPE 0 SEGMENT SIZE 80,
CONSTRAINT "PK_CODPESSOA" PRIMARY KEY ("CODPESSOA")
);
ALTER TABLE "TBPESSOA" ADD CONSTRAINT "FK_CIDADENACIMENTO" FOREIGN KEY ("CODCIDADENACIMENTO") REFERENCES TBCIDADE ("CODCIDADE");
ALTER TABLE "TBPESSOA" ADD CONSTRAINT "FK_CIDRESIDENDCIA" FOREIGN KEY ("CODCIDRESID") REFERENCES TBCIDADE ("CODCIDADE");

CREATE TABLE "TBALUGUEL"
(
  "CODALUGUEL"	DECIMAL(15,0) NOT NULL,
  "CODPESSOA"	DECIMAL(15,0) NOT NULL,
  "RETIRADA"	DATE NOT NULL,
  "ENTREGA"	DATE NOT NULL,
  "VALOR"	DECIMAL(4, 2) NOT NULL,
  "PAGO"	DECIMAL(4, 2) NOT NULL,
CONSTRAINT "PK_CODALUGUEL_ALUGUEL" PRIMARY KEY ("CODALUGUEL")
);
ALTER TABLE "TBALUGUEL" ADD CONSTRAINT "FK_CODPESSOA_ALUGUEL" FOREIGN KEY ("CODPESSOA") REFERENCES TBPESSOA ("CODPESSOA");

CREATE TABLE "TBDESCCAIXA"
(
  "CODDESCRICAO"	DECIMAL(15,0) NOT NULL,
  "DESCRICAO"	VARCHAR(45) NOT NULL,
 PRIMARY KEY ("CODDESCRICAO")
);

CREATE TABLE "TBGERCONTA"
(
  "CODGERCONTA"	DECIMAL(15,0) NOT NULL,
  "NOME"	VARCHAR(35),
  "ATIVO"	CHAR(3),
CONSTRAINT "PK_CODGERCONTA" PRIMARY KEY ("CODGERCONTA")
);

CREATE TABLE "TBCLIENTE"
(
  "CODCLIENTE"	DECIMAL(15,0) NOT NULL,
  "CODPESSOA"	DECIMAL(15,0) NOT NULL,
  "APELIDO"	VARCHAR(35),
  "CORE"	VARCHAR(20),
  "CONTATONOME"	VARCHAR(45),
  "CONTATORAMAL"	VARCHAR(5),
  "CONTATOENDERECO"	VARCHAR(45),
  "CONTATONBAIRRO"	VARCHAR(35),
  "CONTATOCOMPLEMENTO"	VARCHAR(35),
  "CONTATOCIDADEID"	INTEGER,
  "CONTATOCEP"	VARCHAR(10),
  "CODGERCONTA"	DECIMAL(15,0),
  "CONTA"	VARCHAR(25),
  "FAVORECIDO"	VARCHAR(35),
  "PROPRIETARIO"	CHAR(3) DEFAULT 'Não' NOT NULL,
  "FIADOR"	CHAR(3) DEFAULT 'Não' NOT NULL,
  "FORNECEDOR"	CHAR(3) DEFAULT 'Não' NOT NULL,
  "FUNCIONARIO"	CHAR(3) DEFAULT 'Não' NOT NULL,
  "LOCADOR"	CHAR(3) DEFAULT 'Não' NOT NULL,
  "COMPRADOR"	CHAR(3) DEFAULT 'Não' NOT NULL,
  "CONTATOTEL"	VARCHAR(13),
  "INTERESSADO"	CHAR(3) NOT NULL,
  "TITULAR"	CHAR(3) DEFAULT 'Sim' NOT NULL,
  "RECEBEEMAIL"	CHAR(3) DEFAULT 'Não',
  "PROFISSAO"	VARCHAR(35),
  "CODTITULAR"	DECIMAL(15,0),
  "ATIVO"	CHAR(3) DEFAULT 'Sim' NOT NULL,
  "EMPRESA"	CHAR(3) NOT NULL,
CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("CODCLIENTE")
);
ALTER TABLE "TBCLIENTE" ADD CONSTRAINT "FK_CODGERCONTA_CLIENTE" FOREIGN KEY ("CODGERCONTA") REFERENCES TBGERCONTA ("CODGERCONTA");
ALTER TABLE "TBCLIENTE" ADD CONSTRAINT "FK_CODTITULAR_CLIENTE" FOREIGN KEY ("CODTITULAR") REFERENCES TBCLIENTE ("CODCLIENTE");
ALTER TABLE "TBCLIENTE" ADD CONSTRAINT "FK_PESSOA_CLIENTE" FOREIGN KEY ("CODPESSOA") REFERENCES TBPESSOA ("CODPESSOA");

CREATE TABLE "TBCAIXA"
(
  "CODCAIXA"	DECIMAL(15,0) NOT NULL,
  "CODEMPRESA"	DECIMAL(15,0) NOT NULL,
  "CODDESCRICAO"	INTEGER NOT NULL,
  "VALOR"	DECIMAL(9, 2) NOT NULL,
  "TIPO"	CHAR(1) NOT NULL,
  "LANCAMENTO"	DATE NOT NULL,
CONSTRAINT "PK_CODCAIXA_CAIXA" PRIMARY KEY ("CODCAIXA")
);
ALTER TABLE "TBCAIXA" ADD CONSTRAINT "FK_CODDESCRICAO_CAIXA" FOREIGN KEY ("CODDESCRICAO") REFERENCES TBDESCCAIXA ("CODDESCRICAO");
ALTER TABLE "TBCAIXA" ADD CONSTRAINT "FK_CODEMPRESA_CAIXA" FOREIGN KEY ("CODEMPRESA") REFERENCES TBCLIENTE ("CODCLIENTE");

CREATE TABLE "TBDEBITO"
(
  "CODDEBITO"	DECIMAL(15,0) NOT NULL,
  "CODFICHA"	DECIMAL(15,0) NOT NULL,
  "VALOR"	DECIMAL(4, 2) NOT NULL,
  "VENCIMENTO"	DATE NOT NULL,
CONSTRAINT "PK_CODDEBITO_DEBITO" PRIMARY KEY ("CODDEBITO"),
CONSTRAINT "UK_CODFICHA_DEBITO" UNIQUE ("CODFICHA")
);
ALTER TABLE "TBDEBITO" ADD CONSTRAINT "FK_CODFICHA_DEBITO" FOREIGN KEY ("CODFICHA") REFERENCES TBCLIENTE ("CODCLIENTE");

CREATE TABLE "TBGENERO"
(
  "CODGENERO"	DECIMAL(15,0) NOT NULL,
  "NOME"	VARCHAR(20) NOT NULL,
CONSTRAINT "PK_CODGENERO_GENERO" PRIMARY KEY ("CODGENERO"),
CONSTRAINT "UK_NOME_GENERO" UNIQUE ("NOME")
);

CREATE TABLE "TBPRECO"
(
  "CODPRECO"	DECIMAL(15,0) NOT NULL,
  "NOME"	VARCHAR(45) NOT NULL,
  "VALOR"	DECIMAL(9, 2) NOT NULL,
CONSTRAINT "PK_CODPRECO_PRECO" PRIMARY KEY ("CODPRECO"),
CONSTRAINT "UK_NOME_PRECO" UNIQUE ("NOME")
);

CREATE TABLE "TBFILME"
(
  "CODFILME"	DECIMAL(15,0) NOT NULL,
  "CODIGO"      INTEGER NOT NULL,
  "CODFORNECEDOR"	INTEGER NOT NULL,
  "CODPRECO"	DECIMAL(15,0) NOT NULL,
  "CODGENERO"	DECIMAL(15,0) NOT NULL,
  "NOME"	VARCHAR(50) NOT NULL,
  "AUTOR"	VARCHAR(30),
  "DVD"	CHAR(3) NOT NULL,
  "DATAAQU"	DATE NOT NULL,
  "QUANTIDADE"	INTEGER NOT NULL,
  "SINOPSE"	BLOB SUB_TYPE 0 SEGMENT SIZE 80,
  "ESTANTE"	VARCHAR(10),
  "VALORCOMPRA"	DECIMAL(9, 0),
  "PARTICIP1"	VARCHAR(30),
  "PARTICIP2"	VARCHAR(30),
  "PARTICIP3"	VARCHAR(30),
  "PRATELEIRA"	VARCHAR(10),
CONSTRAINT "PK_CODFILME_FILME" PRIMARY KEY ("CODFILME")
);
ALTER TABLE "TBFILME" ADD CONSTRAINT "FK_CODFONECEDOR_FILME" FOREIGN KEY ("CODFORNECEDOR") REFERENCES TBCLIENTE ("CODCLIENTE");
ALTER TABLE "TBFILME" ADD CONSTRAINT "FK_CODGENERO_FILME" FOREIGN KEY ("CODGENERO") REFERENCES TBGENERO ("CODGENERO");
ALTER TABLE "TBFILME" ADD CONSTRAINT "FK_CODPRECO_FILME" FOREIGN KEY ("CODPRECO") REFERENCES TBPRECO ("CODPRECO");

CREATE TABLE "TBFITA"
(
  "SUBCOD"	VARCHAR(10) NOT NULL,
  "CODFILME"	DECIMAL(15,0) NOT NULL,
  "DISPONIVEL"	CHAR(3) NOT NULL,
  "BARCODE"	VARCHAR(40),
CONSTRAINT "PK_SUBCOD_FITA" PRIMARY KEY ("SUBCOD")
);
ALTER TABLE "TBFITA" ADD CONSTRAINT "FK_CODFILME_FITA" FOREIGN KEY ("CODFILME") REFERENCES TBFILME ("CODFILME");

CREATE TABLE "TBGRUPOUSUARIO"
(
  "CODGRUPOUSUARIO"	DECIMAL(15,0) NOT NULL,
  "NOME"	VARCHAR(35),
CONSTRAINT "PK_CODGRUPOUSUARIO_GRUPOUSUARIO" PRIMARY KEY ("CODGRUPOUSUARIO")
);

CREATE TABLE "TBGRUPOIMPRESSAO"
(
  "CODGRUPOUSUARIO"	DECIMAL(15,0) NOT NULL,
  "CAPTION"	VARCHAR(50) NOT NULL,
  "NOME"	VARCHAR(50) NOT NULL,
  "IMPRIMIR"	CHAR(3) NOT NULL
);
ALTER TABLE "TBGRUPOIMPRESSAO" ADD CONSTRAINT "FK_CODGRUPOUSUARIO_IMPRESSAO" FOREIGN KEY ("CODGRUPOUSUARIO") REFERENCES TBGRUPOUSUARIO ("CODGRUPOUSUARIO");

CREATE TABLE "TBGRUPOINTERFACE"
(
  "CODGRUPOUSUARIO"	DECIMAL(15,0) NOT NULL,
  "CAPTION"	VARCHAR(50) NOT NULL,
  "NOME"	VARCHAR(50) NOT NULL,
  "SOMENTELEITURA"	CHAR(3) NOT NULL,
  "INSERIR"	CHAR(3) NOT NULL,
  "ALTERAR"	CHAR(3) NOT NULL,
  "IMPRIMIR"	CHAR(3) NOT NULL,
  "EXCLUIR"	CHAR(3) NOT NULL
);
ALTER TABLE "TBGRUPOINTERFACE" ADD CONSTRAINT "FK_CODGRUPOUSUARIO_INTERFACE" FOREIGN KEY ("CODGRUPOUSUARIO") REFERENCES TBGRUPOUSUARIO ("CODGRUPOUSUARIO");

CREATE TABLE "TBHISTORICO"
(
  "CODHISTORICO"	DECIMAL(15,0) NOT NULL,
  "CODFICHA"	DECIMAL(15,0) NOT NULL,
  "CODFILME"	DECIMAL(15,0),
  "DATASAIDA"	DATE,
  "DATAENTRADA"	DATE,
  "ATRASO"	CHAR(3),
  "CODSOCIO"	DECIMAL(15,0),
  "QTD"	INTEGER,
  "TROCA"	CHAR(3),
  "MOTIVO"	VARCHAR(255),
  "VALOR"	DECIMAL(9, 2),
CONSTRAINT "PK_CODHISTORICO_HISTORICO" PRIMARY KEY ("CODHISTORICO")
);

CREATE TABLE "TBITEMALUGUEL"
(
  "CODITEMALUG"	DECIMAL(15,0) NOT NULL,
  "CODALUGUEL"	DECIMAL(15,0) NOT NULL,
  "SUBCOD"	VARCHAR(10) NOT NULL,
  "VALOR"	DECIMAL(4, 2) NOT NULL,
  "DEVOLVE"	CHAR(3) NOT NULL,
  "CODFILME"	DECIMAL(15,0) NOT NULL,
CONSTRAINT "PK_CODITEMALUG_ITEMALUG" PRIMARY KEY ("CODITEMALUG"),
CONSTRAINT "UK_SUBCOD_ITEMALUGUEL" UNIQUE ("SUBCOD")
);
ALTER TABLE "TBITEMALUGUEL" ADD CONSTRAINT "FK_CODALUGUEL_ITEMALUGUEL" FOREIGN KEY ("CODALUGUEL") REFERENCES TBALUGUEL ("CODALUGUEL");
ALTER TABLE "TBITEMALUGUEL" ADD CONSTRAINT "FK_CODFILME_ITEMALUGUEL" FOREIGN KEY ("CODFILME") REFERENCES TBFILME ("CODFILME");
ALTER TABLE "TBITEMALUGUEL" ADD CONSTRAINT "FK_SUBCOD_ITEMALUGUEL" FOREIGN KEY ("SUBCOD") REFERENCES TBFITA ("SUBCOD");

CREATE TABLE "TBOBS"
(
  "CODOBS"	DECIMAL(15,0) NOT NULL,
  "DATAOBS"	DATE NOT NULL,
  "OBS"	VARCHAR(255) NOT NULL,
  "CODPESSOA"	DECIMAL(15,0) NOT NULL,
CONSTRAINT "PK_CODOBS_OBS" PRIMARY KEY ("CODOBS")
);
ALTER TABLE "TBOBS" ADD CONSTRAINT "FK_CODPESSOA_OBS" FOREIGN KEY ("CODPESSOA") REFERENCES TBPESSOA ("CODPESSOA");

CREATE TABLE "TBRESERVA"
(
  "CODRESERVA"	DECIMAL(15,0) NOT NULL,
  "SUBCOD"	VARCHAR(10) NOT NULL,
  "CODPESSOA"	DECIMAL(15,0) NOT NULL,
  "RESERVA"	DATE NOT NULL,
  "CODCLIENTE"	DECIMAL(15,0) NOT NULL,
CONSTRAINT "PK_CODRESERVA_RESERVA" PRIMARY KEY ("CODRESERVA")
);
ALTER TABLE "TBRESERVA" ADD CONSTRAINT "FK_CODCLIENTE_RESERVA" FOREIGN KEY ("CODCLIENTE") REFERENCES TBCLIENTE ("CODCLIENTE");
ALTER TABLE "TBRESERVA" ADD CONSTRAINT "FK_CODPESSOA_RESERVA" FOREIGN KEY ("CODPESSOA") REFERENCES TBPESSOA ("CODPESSOA");
ALTER TABLE "TBRESERVA" ADD CONSTRAINT "FK_SUBCOD_RESERVA" FOREIGN KEY ("SUBCOD") REFERENCES TBFITA ("SUBCOD");

CREATE TABLE "TBUSUARIO"
(
  "CODUSUARIO"	DECIMAL(15,0) NOT NULL,
  "CODPESSOA"	DECIMAL(15,0) NOT NULL,
  "LOGIN"	VARCHAR(16) NOT NULL,
  "SENHA"	VARCHAR(16) NOT NULL,
  "ULTIMASENHA"	VARCHAR(16) NOT NULL,
  "DATAEXPIRACAO"	DATE NOT NULL,
  "ATIVO"	CHAR(3) NOT NULL,
CONSTRAINT "PK_CODUSUARIO" PRIMARY KEY ("CODUSUARIO")
);

CREATE TABLE "TBUSUARIOGRUPO"
(
  "CODUSUARIO"	DECIMAL(15,0) NOT NULL,
  "CODGRUPOUSUARIO"	DECIMAL(15,0) NOT NULL
);
ALTER TABLE "TBUSUARIOGRUPO" ADD CONSTRAINT "FK_CODUSUARIO_GRPUSUARIO" FOREIGN KEY ("CODUSUARIO") REFERENCES TBUSUARIO ("CODUSUARIO");

