  DELETE FROM TBAGENCIA;
  DELETE FROM TBITEMALUGUEL;
  DELETE FROM TBALUGUEL;
  DELETE FROM TBBANCO;
  DELETE FROM TBCAIXA;
  DELETE FROM TBDEBITO;
  DELETE FROM TBRESERVA;
  DELETE FROM TBFITA;
  DELETE FROM TBFILME;
  DELETE FROM TBGENERO;
  DELETE FROM TBPRECO;
  DELETE FROM TBGRUPOIMPRESSAO;
  DELETE FROM TBGRUPOINTERFACE;
  DELETE FROM TBGRUPOUSUARIO;
  DELETE FROM TBHISTORICO;
  DELETE FROM TBMENSAGEM;
  DELETE FROM TBOBS;
  DELETE FROM TBUSUARIOGRUPO;
  DELETE FROM TBGRUPOUSUARIO;
  DELETE FROM TBUSUARIO;
  UPDATE TBCLIENTE SET CODTITULAR = NULL;
  DELETE FROM TBCLIENTE;
  DELETE FROM TBPROPRIEDADE;
  DELETE FROM TBPESSOA;
  DELETE FROM TBGERCONTA;
  DROP TABLE TBCOMANDCAMPOS;
  DROP TABLE TBCOMANDOSQL;
  DROP TABLE TBCONFIGCONTRATO;
  DROP TABLE TBDOCCONTRATO;
  DROP TABLE TBDOCUMENTO;
  DROP TABLE TBNOMEDESPESA;
  DROP TABLE TBPROPRIEDADE;
  DROP TABLE TBTIPOIMOVEL;
  DROP TABLE TBRUA;
  DROP TABLE TBBAIRRO;
  DROP TABLE TBCONTRATO;
  COMMIT;


  
  
  

