INSERT INTO "TBPESSOA" ("CODPESSOA", "CODCIDRESID", "CODUSUARIO", "ENDERECO", "COMPLEMENTO", "BAIRRO", "TEL", "CEL", "CEP", "NOME", "TIPOPESSOA", "CPFCNPJ", "EMAIL", "WEB", "DATACADASTRO", "DATATUALIZACAO", "RG", "DATANASCIMENTO", "SEXO", "TELRAMAL", "CODCIDADENACIMENTO", "DEFICIECIA", "ESTADOCIVIL" ) VALUES (2, 2121, 1, 'Rua Guaçuí 427/204A', '', 'São Mateus', '(32)3233-2211', '(32)9195-6777', '', 'Mundo Conecto', 'J', '48.956.457/4524-25', 'willimar@mundoconecto.eti.br', 'www.mundoconecto.eti.br', '20/12/2005', '20/12/2005', '', '20/12/2005', NULL, NULL, 2121, '', NULL);
INSERT INTO "TBPESSOA" ("CODPESSOA", "CODCIDRESID", "CODUSUARIO", "ENDERECO", "COMPLEMENTO", "BAIRRO", "TEL", "CEL", "CEP", "NOME", "TIPOPESSOA", "CPFCNPJ", "EMAIL", "WEB", "DATACADASTRO", "DATATUALIZACAO", "RG", "DATANASCIMENTO", "SEXO", "TELRAMAL", "CODCIDADENACIMENTO", "DEFICIECIA", "ESTADOCIVIL" ) VALUES (1, 2121, -1, 'Rua Guaçuí 427/204 A', '', 'São Mateus', '(32)3233-2211', '(32)9195-6777', '36025-190', 'Administrador', 'F', '000.000.000-00', 'willimar@mundoconecto.eti.br', 'www.mundoconecto.eti.br', '2/12/2005', '2/12/2005', '', '2/12/2005', 'M', NULL, 2121, '', 1);

INSERT INTO "TBDESCCAIXA" ("CODDESCRICAO", "DESCRICAO") VALUES (1, 'Venda de Filme');
INSERT INTO "TBDESCCAIXA" ("CODDESCRICAO", "DESCRICAO") VALUES (2, 'Locação de Filme (Pagamento Devolução)');
INSERT INTO "TBDESCCAIXA" ("CODDESCRICAO", "DESCRICAO") VALUES (3, 'Locação de Filme (Pagamento Saída)');
INSERT INTO "TBDESCCAIXA" ("CODDESCRICAO", "DESCRICAO") VALUES (4, 'Quitação de Debito');
INSERT INTO "TBDESCCAIXA" ("CODDESCRICAO", "DESCRICAO") VALUES (5, 'Sangria');
INSERT INTO "TBDESCCAIXA" ("CODDESCRICAO", "DESCRICAO") VALUES (6, 'Suprimento');

INSERT INTO "TBCLIENTE" ("CODCLIENTE", "CODPESSOA", "APELIDO", "CORE", "CONTATONOME", "CONTATORAMAL", "CONTATOENDERECO", "CONTATONBAIRRO", "CONTATOCOMPLEMENTO", "CONTATOCIDADEID", "CONTATOCEP", "CODGERCONTA", "CONTA", "FAVORECIDO", "PROPRIETARIO", "FIADOR", "FORNECEDOR", "FUNCIONARIO", "LOCADOR", "COMPRADOR", "CONTATOTEL", "INTERESSADO", "TITULAR", "RECEBEEMAIL", "PROFISSAO", "CODTITULAR", "ATIVO", "EMPRESA") VALUES (2, 2, 'Mundo Conecto', NULL, 'Willimar Augusto Rocha', '', NULL, NULL, NULL, 2121, NULL, NULL, NULL, NULL, 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', '(32)3233-2211', 'Não', 'Não', 'Não', 'Automação', NULL, 'Sim', 'Sim');
INSERT INTO "TBCLIENTE" ("CODCLIENTE", "CODPESSOA", "APELIDO", "CORE", "CONTATONOME", "CONTATORAMAL", "CONTATOENDERECO", "CONTATONBAIRRO", "CONTATOCOMPLEMENTO", "CONTATOCIDADEID", "CONTATOCEP", "CODGERCONTA", "CONTA", "FAVORECIDO", "PROPRIETARIO", "FIADOR", "FORNECEDOR", "FUNCIONARIO", "LOCADOR", "COMPRADOR", "CONTATOTEL", "INTERESSADO", "TITULAR", "RECEBEEMAIL", "PROFISSAO", "CODTITULAR", "ATIVO", "EMPRESA") VALUES (1, 1, NULL, NULL, 'Willimar Augusto Rocha', NULL, 'Rua Guaçuí 427/204 A', 'São Mateus', NULL, 2121, '36025-190', NULL, NULL, NULL, 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', '(32)3233-2211', 'Não', 'Não', 'Não', 'Administrador de dados', NULL, 'Sim', 'Não');

INSERT INTO "TBGRUPOUSUARIO" ("CODGRUPOUSUARIO", "NOME") VALUES (1, 'Administradores');

INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Aniversariantes', 'Aniversariantes1', 'Sim');
INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Em débito', 'EmDbito1', 'Sim');
INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Montar catalogo', 'Montarcatalogo1', 'Sim');
INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Caixa corrente', 'Caixacorrente1', 'Sim');
INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Fechamento', 'Fechamento1', 'Sim');
INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Detalhado', 'Detalhado1', 'Sim');
INSERT INTO "TBGRUPOIMPRESSAO" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "IMPRIMIR") VALUES (1, 'Detalhado Completo', 'DetalhadoCompleto1', 'Sim');

INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Sócios', 'Clientes1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Forncedores', 'Forncedor1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Generos', 'Genero1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Preços', 'Preos1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Filmes', 'Filmes2', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Locação', 'Locao1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Venda', 'Venda1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Reserva de Fita', 'ReservadeFita1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Pagamentos', 'ClientesemDebito1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Grupos', 'Grupos1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Funcionários', 'Usurios2', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Fluxo de Caixa', 'FluxodeCaixa1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');
INSERT INTO "TBGRUPOINTERFACE" ("CODGRUPOUSUARIO", "CAPTION", "NOME", "SOMENTELEITURA", "INSERIR", "ALTERAR", "IMPRIMIR", "EXCLUIR") VALUES (1, 'Empresa', 'Empresa1', 'Não', 'Sim', 'Sim', 'Sim', 'Sim');

INSERT INTO "TBUSUARIO" ("CODUSUARIO", "CODPESSOA", "LOGIN", "SENHA", "ULTIMASENHA", "DATAEXPIRACAO", "ATIVO") VALUES (1, 1, 'Administrador', 'ÍÐÙ', '­ÐÙÕÚÕßàÞÍÐÛÞ', '10/10/1010', 'Sim');

INSERT INTO "TBUSUARIOGRUPO" ("CODUSUARIO", "CODGRUPOUSUARIO") VALUES (1, 1);
